apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-didac-api
  labels:
    app: teacher-didac-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-didac-api-app
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: teacher-didac-api-app
    spec:
      containers:
      - name: teacher-didac-api-app
        image: booij/teacherdidac.web
        ports:
        - containerPort: {{.Values.deployment.ports.api.containerPort}}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{.Values.deployment.environment}}
        - name: AUTH_SERVER_URL
          valueFrom: 
            configMapKeyRef:
              name: teacher-didac-configmap
              key: auth.url

              
---
apiVersion: v1
kind: Service
metadata:
  name: teacher-didac-scheduler-service
spec:
  selector:
    app: teacher-didac-scheduler-app
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: {{.Values.deployment.ports.api.containerPort}}
      targetPort: {{.Values.deployment.ports.api.containerPort}}
      nodePort: {{.Values.deployment.ports.api.nodePort}}

