apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-didac-api
  labels:
    app: teacher-didac-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-didac-api-deployment
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: teacher-didac-api-deployment
    spec:      
      volumes:
      - name: google-service-secret
        secret:
          secretName: google-service-secret
      containers:
      - name: teacher-didac-api-deployment
        image: booij/teacher-didac.api
        imagePullPolicy: {{.Values.deployment.image.pullPolicy}}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: {{.Values.deployment.resources.api.requestMemory}}
            cpu: {{.Values.deployment.resources.api.requestCPU}}
          limits:
            memory: {{.Values.deployment.resources.api.limitMemory}}
            cpu: {{.Values.deployment.resources.api.limitCPU}}
        volumeMounts:
        - name: google-service-secret
          # all contents inside /app/File/config are overwritten
          mountPath: "/app/Files/config"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{.Values.deployment.environment}}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: {{.Values.deployment.database.firebase.serviceAccountLocation}}
        - name: AUTH_SERVER_URL
          valueFrom: 
            configMapKeyRef:
              name: teacher-didac-configmap
              key: auth-url
---
apiVersion: v1
kind: Service
metadata:
  name: teacher-didac-api-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "didac-api-loadbalancer"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "80"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/index.html"
spec:
  selector:
    app: teacher-didac-api-deployment
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

