apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-didac-api-deployment
  labels:
    app: teacher-didac-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-didac-api-deployment
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: teacher-didac-api-deployment
    spec:
      containers:
      - name: teacher-didac-api-deployment
        image: booij/teacherdidac.api
        ports:
        - containerPort: {{.Values.deployment.ports.api.containerPort}}
        resources:
          requests:
            memory: {{.Values.deployment.resources.api.requestMemory}}
            cpu: {{.Values.deployment.resources.api.requestCPU}}
          limits:
            memory: {{.Values.deployment.resources.api.limitMemory}}
            cpu: {{.Values.deployment.resources.api.limitCPU}}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{.Values.deployment.environment}}
        - name: AUTH_SERVER_URL
          valueFrom: 
            configMapKeyRef:
              name: teacher-didac-configmap
              key: auth.url


---
apiVersion: v1
kind: Service
metadata:
  name: teacher-didac-api-service
spec:
  selector:
    app: teacher-didac-api-deployment
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: {{.Values.deployment.ports.api.containerPort}}
      targetPort: {{.Values.deployment.ports.api.containerPort}}
      nodePort: {{.Values.deployment.ports.api.nodePort}}

