apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-didac-app
  labels:
    app: teacher-didac-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-didac-app-deployment
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: teacher-didac-app-deployment
    spec:
      containers:
      - name: teacher-didac-app-deployment
        image: booij/teacherdidac.app
        imagePullPolicy: {{.Values.deployment.image.pullPolicy}}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: {{.Values.deployment.resources.app.requestMemory}}
            cpu: {{.Values.deployment.resources.app.requestCPU}}
          limits:
            memory: {{.Values.deployment.resources.app.limitMemory}}
            cpu: {{.Values.deployment.resources.app.limitCPU}}
        env:
        - name: API_SERVER_URL
          valueFrom: 
            configMapKeyRef:
              name: teacher-didac-configmap
              key: api-url

              
---
apiVersion: v1
kind: Service
metadata:
  name: teacher-didac-app-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "didac-app-loadbalancer"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/"
spec:
  selector:
    app: teacher-didac-app-deployment
  type: LoadBalancer  
  externalTrafficPolicy: Local
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

