apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-didac-auth
  labels:
    app: teacher-didac-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-didac-auth-app
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: teacher-didac-auth-app
    spec:
      containers:
      - name: teacher-didac-auth-app
        image: booij/authentication.server
        ports:
        - containerPort: {{.Values.deployment.ports.auth.containerPort}}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{.Values.deployment.environment}}
        - name: DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: teacher-didac-configmap
              key: database.main.host
        - name: DB_NAME
          value: IdentityDb
        - name: DB_USER
          value: {{.Values.deployment.database.main.user}}
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: teacher-didac-secret
              key: database.main.password
        - name: JWT_SECRETTKEY
          valueFrom: 
            secretKeyRef:
              name: teacher-didac-secret
              key: jwt.key
        - name: JWT_ISSUER
          valueFrom: 
            secretKeyRef:
              name: teacher-didac-secret
              key: jwt.issuer
        - name: EMAIL_APPKEY
          valueFrom: 
            secretKeyRef:
              name: teacher-didac-secret
              key: email.appkey
---
apiVersion: v1
kind: Service
metadata:
  name: teacher-didac-email-service
spec:
  selector:
    app: teacher-didac-email-app
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: {{.Values.deployment.ports.auth.containerPort}}
      targetPort: {{.Values.deployment.ports.auth.containerPort}}
      nodePort: {{.Values.deployment.ports.auth.nodePort}}

