apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-didac-email
  labels:
    app: teacher-didac-email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-didac-email-deployment
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: teacher-didac-email-deployment
    spec:
      containers:
      - name: teacher-didac-email-deployment
        image: booij/email.service
        ports:
        - containerPort: {{.Values.deployment.ports.email.containerPort}}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{.Values.deployment.environment}}
---
apiVersion: v1
kind: Service
metadata:
  name: teacher-didac-email-service
spec:
  selector:
    app: teacher-didac-email-deployment
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: {{.Values.deployment.ports.email.containerPort}}
      targetPort: {{.Values.deployment.ports.email.containerPort}}
      nodePort: {{.Values.deployment.ports.email.nodePort}}

