apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: teacher-didac-main-db-deployment
  labels:
    app: mongodb
spec:
  serviceName: teacher-didac-main-db-service
  selector:
    matchLabels:
      app: teacher-didac-main-db
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: teacher-didac-main-db
    spec:
      containers:
        - name: teacher-didac-main-db
          image: mysql
          ports:
          - containerPort: {{.Values.deployment.ports.mainDb.containerPort}}
          env:
          - name: ASPNETCORE_ENVIRONMENT
            valueFrom: 
              secretKeyRef:
                name: teacher-didac-secret
                key: database.main.password
          volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: main-db-claim


---
apiVersion: v1
kind: Service
metadata:
  name: teacher-didac-main-db-service
spec:
  selector:
    app: teacher-didac-main-db
  ports:
    - protocol: TCP
      port: {{.Values.deployment.ports.mainDb.containerPort}}
      targetPort: {{.Values.deployment.ports.mainDb.containerPort}}
      nodePort: {{.Values.deployment.ports.mainDb.nodePort}}


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: main-db-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.deployment.database.main.storageCapacity}}
