apiVersion: v1
kind: PersistentVolume
metadata:
  name: teacher-didac-volume
  labels:
    type: local
spec:
  #we use local node storage here!
  storageClassName: hostpath
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"