apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-didac-email
  labels:
    app: teacher-didac-email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-didac-scheduler-deployment
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: teacher-didac-scheduler-deployment
    spec:
      containers:
      - name: teacher-didac-scheduler-deployment
        image: booij/teacherdidac.scheduler
        ports:
        - containerPort: {{.Values.deployment.ports.scheduler.containerPort}}
        resources:
          requests:
            memory: {{.Values.deployment.resources.scheduler.requestMemory}}
            cpu: {{.Values.deployment.resources.scheduler.requestCPU}}
          limits:
            memory: {{.Values.deployment.resources.scheduler.limitMemory}}
            cpu: {{.Values.deployment.resources.scheduler.limitCPU}}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{.Values.deployment.environment}}
        - name: DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: teacher-didac-configmap
              key: database.main.host
        - name: DB_NAME
          value: ScheduleDb
        - name: DB_USER
          value: {{.Values.deployment.database.main.user}}
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: teacher-didac-secret
              key: database.main.password
        - name: HANGFIRE_USER
          value: {{.Values.deployment.hangfire.user}}
        - name: HANGFIRE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: teacher-didac-secret
              key: hangfire.password

              
---
apiVersion: v1
kind: Service
metadata:
  name: teacher-didac-scheduler-service
spec:
  selector:
    app: teacher-didac-scheduler-deployment
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: {{.Values.deployment.ports.scheduler.containerPort}}
      targetPort: {{.Values.deployment.ports.scheduler.containerPort}}
      nodePort: {{.Values.deployment.ports.scheduler.nodePort}}

