apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-didac-scheduler
  labels:
    app: teacher-didac-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-didac-scheduler-deployment
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: teacher-didac-scheduler-deployment
    spec:
      volumes:
      - name: google-service-secret
        secret:
          secretName: google-service-secret
      containers:
      - name: teacher-didac-scheduler-deployment
        image: booij/teacher-didac.scheduler
        imagePullPolicy: {{.Values.deployment.image.pullPolicy}}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: {{.Values.deployment.resources.scheduler.requestMemory}}
            cpu: {{.Values.deployment.resources.scheduler.requestCPU}}
          limits:
            memory: {{.Values.deployment.resources.scheduler.limitMemory}}
            cpu: {{.Values.deployment.resources.scheduler.limitCPU}}
        volumeMounts:
        - name: google-service-secret
          # all contents inside /app/File/config are overwritten
          mountPath: "/app/Files/config"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{.Values.deployment.environment}}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: {{.Values.deployment.database.firebase.serviceAccountLocation}}
        - name: DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: teacher-didac-configmap
              key: database-main-host
        - name: DB_NAME
          value: ScheduleDb
        - name: DB_USER
          value: {{.Values.deployment.database.main.user}}
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: teacher-didac-secret
              key: database-main-password
        - name: HANGFIRE_USER
          value: {{.Values.deployment.hangfire.user}}
        - name: HANGFIRE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: teacher-didac-secret
              key: hangfire-password

              
---
apiVersion: v1
kind: Service
metadata:
  name: teacher-didac-scheduler-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "didac-scheduler-loadbalancer"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/api/Hangfire"
spec:
  selector:
    app: teacher-didac-scheduler-deployment
  type: LoadBalancer 
  externalTrafficPolicy: Local 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
