apiVersion: v1
kind: Secret
metadata: 
  name: teacher-didac-secret
type: Opaque
data:
  database-main-password: {{.Values.deployment.database.main.password}}
  hangfire-password: {{.Values.deployment.hangfire.password}}
  jwt-key: {{.Values.deployment.jwt.key}}
  jwt-issuer: {{.Values.deployment.jwt.issuer}}
  email-appkey: {{.Values.deployment.email.appkey}}

---

apiVersion: v1
kind: Secret
metadata: 
  name: google-service-secret
data:
  firebase-admin-secret.json: {{.Values.deployment.database.firebase.serviceAccountContent}}
