import { FEEDBACK_OPTION_INPUT } from "../enums/answers.enum";


export const DECK_DEFAULT_FEEDBACKOPTION = FEEDBACK_OPTION_INPUT
export const DECK_DEFAULT_LEARNING_STEPS = [15, 30]
export const DECK_DEFAULT_DEFAULT_EASE_MODIFIER = 250;
export const DECK_DEFAULT_FIRST_LEARNING_INTERVAL = 10;
export const DECK_DEFAULT_INTERVAL_MODIFIER = 100;
export const DECK_DEFAULT_EASE_BONUS = 130;
export const DECK_DEFAULT_EASE_PENALTY = 70;
export const DECK_DEFAULT_AGAIN = 80;
export const DECK_DEFAULT_HARD = 85;
export const DECK_DEFAULT_GOOD = 100;
export const DECK_DEFAULT_EASY = 115;
