version: '3.8'

services:
    app:
        image: 'my-angular-app'
        build: 
          context: .
          dockerfile: stage.Dockerfile
        restart: always
        ports:
          - 4300:4200