deployment:
  environment: PRODUCTION
  database:
    main:
      host: teacherdidac.db
      user: ${MAIN_DATABASE_USER}
      password: ${MAIN_DATABASE_PASSWORD}
      storageCapacity: 10Gi
  hangfire: 
    user: ${HANGFIRE_USER}
    password: ${HANGFIRE_PASSWORD}
  jwt:
    key: ${JWT_KEY}
    issuer: ${JWT_ISSUER}
  email:
    appkey: ${EMAIL_APPKEY}
  auth:
    url: http://teacherdidac.authentication
  api:
    url: http://teacherdidac.api
  ports:
    api:
      containerPort: 7000
      nodePort: 37000
    auth:
      containerPort: 3000
      nodePort: 33000
    email:
      containerPort: 2000
      nodePort: 32000
    scheduler:
      containerPort: 7001
      nodePort: 37001
    mainDB:
      containerPort: 3003
      nodePort: 33003



