version: '3.8'

services:

    
  teacherdidac.web:
    image: ${DOCKER_REGISTRY-}teacherdidacweb
    build:
      context: .
      dockerfile: TeacherDidac.Web/Dockerfile
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/Files/config/firebase-admin-secret.json

      
  teacherdidac.scheduler:
    image: ${DOCKER_REGISTRY-}teacherdidacscheduler
    build:
      context: .
      dockerfile: TeacherDidac.Scheduler/Dockerfile
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/Files/config/firebase-admin-secret.json

  #teacherdidac.ai:
    #image: booij/transcribing-nn.service 
  
  teacherdidac.authentication:
    image: booij/authentication.service 

  teacherdidac.db:
    image: mysql

  teacherdidac.email:
    image: booij/email.service
    
 

networks:
  proxynet:
    name: custom_network


