version: '3.4'

services:
      
  teacherdidac.web:
    depends_on:
      - teacherdidac.authentication
    ports:
      - "7002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      AUTH_SERVER_URL: ${AUTH_SERVER_URL}

  
  teacherdidac.scheduler:
    depends_on:
      - teacherdidac.db
    ports:
      - "7001:80"
    networks:
      - proxynet
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      HANGFIRE_USER: ${HANGFIRE_USER}
      HANGFIRE_PASSWORD: ${HANGFIRE_PASSWORD}



  teacherdidac.authentication:
    ports:
      - "3000:80"   
    volumes:
      - /home/server/files:/app/UploadedFiles
    depends_on: 
      - teacherdidac.db
      - teacherdidac.email
    environment:
      ASPNETCORE_ENVIRONMENT: STAGING        
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRETTKEY: ${JWT_SECRETKEY}
      JWT_ISSUER: ${JWT_ISSUER}
      EMAIL_APPKEY: ${EMAIL_APPKEY}

  teacherdidac.db:
    container_name: teacherdidac.db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3003:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  teacherdidac.email:
    container_name: teacherdidac.email
    ports:
      - "2000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: STAGING