version: '3.8'

services:
      
  teacherdidac.web:
    restart: always
    depends_on:
      - teacherdidac.authentication
    ports:
      - "7002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      AUTH_SERVER_URL: ${AUTH_SERVER_URL}
      RECOGNITION_SERVER_URL: ${RECOGNITION_SERVER_URL}

  
  teacherdidac.scheduler:
    restart: always
    depends_on:
      - teacherdidac.authentication
      - teacherdidac.db
    ports:
      - "7001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      HANGFIRE_USER: ${HANGFIRE_USER}
      HANGFIRE_PASSWORD: ${HANGFIRE_PASSWORD}



  teacherdidac.authentication:
    restart: always
    ports:
      - "3000:80"   
    volumes:
      - /home/server/files:/app/UploadedFiles
    depends_on: 
      - teacherdidac.db
      - teacherdidac.email
    environment:
      ASPNETCORE_ENVIRONMENT: Staging       
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_NAME}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRETKEY: ${JWT_SECRETKEY}
      JWT_ISSUER: ${JWT_ISSUER}
      AUTHENTICATION_URL: ${AUTHENTICATION_URL}
      EMAIL_URL: ${EMAIL_URL}
      EMAIL_APPKEY: ${EMAIL_APPKEY}

  teacherdidac.db:
    restart: always
    container_name: teacherdidac.db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3003:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  teacherdidac.email:
    restart: always
    container_name: teacherdidac.email
    ports:
      - "2000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging

  teacherdidac.transcribing-nn:
    restart: always
    container_name: teacherdidac.transcribing-nn
    ports:
      - "4000:8000"
    entrypoint: ["/bin/sh","-c"]
    command: 
    - |
        python manage.py runserver 0.0.0.0:8000
    environment:
        DJANGO_DEBUG: 'True'

    