name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Didac Api
        uses: docker/build-push-action@v2
        with:
          context: ./API
          file: TeacherDidac.Web/Dockerfile
          push: true
          tags: booij/teacher-didac.api:latest
      -
        name: Build and push Didac Scheduler
        uses: docker/build-push-action@v2
        with:
          context: ./API
          file: TeacherDidac.Scheduler/Dockerfile
          push: true
          tags: booij/teacher-didac.scheduler:latest
      -
        name: Build and push Didac App
        uses: docker/build-push-action@v2
        with:
          context: .
          file: App/nginx.stage.Dockerfile
          push: true
          tags: booij/teacher-didac.scheduler:latest
